class PyttdError(Exception): ...
class RecordingError(PyttdError): ...
class ReplayError(PyttdError): ...
class CheckpointError(PyttdError): ...
class ServerError(PyttdError): ...
class NoForkError(PyttdError): ...
